theme: jekyll-theme-minimal
title: [Cristina Dobre]
show_downloads: ["false"]
description: [Hi there! I'm Cristina! 
If you'd like to get in touch, send me your message at c [dot] dobre [at] gold [dot] ac [dot] uk and tweet/dm me @shesCristina]
